relativeURLs = true
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"
# baseurl = "https://nguyennhung1529.github.io/AWS-Serverless-Data-Lake-Jumpstart/"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "nguyenthinhung1529@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "AWS Serverless Data Lake Jumpstart"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> Nguyen Nhung FCJ"
identifier = "Nguyen Nhung FCJ FB"
url = "https://www.facebook.com/nguyennhung3299"
weight = 20

[Languages.vi]
title = "AWS Serverless Data Lake Jumpstart"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> Nguyen Nhung FCJ"
identifier = "Nguyen Nhung FCJ FB"
url = "https://www.facebook.com/nguyennhung3299"
weight = 20
